/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tbdots_ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import static java.sql.DriverManager.getConnection;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jekko
 */
public class FramePatientUpdate extends javax.swing.JFrame {
    java.sql.Connection conn  = null;
    java.sql.Statement stmt = null;
//    static String url = "jdbc:sqlite:C:\\Users\\Jekko\\Documents\\NetBeansProjects\\TBDOTS_UI\\src\\tbdots_ui\\db.sqlite";
//    
    /**
     * Creates new form FrameUpdate
     */
    public FramePatientUpdate() {
        initComponents();
        setCenterFrame();
        changeIcon();
        this.setResizable(false);
    }
    public void setCenterFrame(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    public void changeIcon(){
        ImageIcon icon = new ImageIcon("src/TBDOTS_UI/ddhlogo1.jpg");
        this.setIconImage(icon.getImage());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txtUpdatePatientID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtUpdateFirstname = new javax.swing.JTextField();
        txtUpdateMiddlename = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtUpdateLastname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jUpdateBirthdate = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        txtUpdateAge = new javax.swing.JTextField();
        btnUpdateMale = new javax.swing.JRadioButton();
        btnUpdateFemale = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtUpdateOccupation = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtUpdateCivilStatus = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtUpdateContactPerson = new javax.swing.JTextField();
        txtUpdateAddress = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtUpdateContactNo = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblBack = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLoad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("UPDATE PATIENT RECORDS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));
        jPanel2.setForeground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 960, 20));

        jPanel6.setBackground(new java.awt.Color(54, 33, 89));
        jPanel6.setForeground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 20));

        jLabel25.setFont(new java.awt.Font("Stencil Std", 1, 36)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("TBDOTS DEPT");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, -1, -1));
        getContentPane().add(txtUpdatePatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 100, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("PATIENT NO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("MIDDLENAME");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        txtUpdateFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateFirstnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUpdateFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 210, 30));
        getContentPane().add(txtUpdateMiddlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 150, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("FIRSTNAME");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("LASTNAME");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, -1, -1));

        txtUpdateLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateLastnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUpdateLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 180, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("SEX");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));
        getContentPane().add(jUpdateBirthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 130, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("BIRTHDATE");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        txtUpdateAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateAgeActionPerformed(evt);
            }
        });
        getContentPane().add(txtUpdateAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 50, 30));

        buttonGroup1.add(btnUpdateMale);
        btnUpdateMale.setText("Male");
        btnUpdateMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMaleActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, -1, 30));

        buttonGroup1.add(btnUpdateFemale);
        btnUpdateFemale.setText("Female");
        getContentPane().add(btnUpdateFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, -1, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("AGE");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("OCCUPATION");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));
        getContentPane().add(txtUpdateOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 300, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("ADDRESS");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("CIVIL STATUS");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        txtUpdateCivilStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateCivilStatusActionPerformed(evt);
            }
        });
        getContentPane().add(txtUpdateCivilStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 190, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("CONTACT PERSON");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        txtUpdateContactPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateContactPersonActionPerformed(evt);
            }
        });
        getContentPane().add(txtUpdateContactPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 200, 32));
        getContentPane().add(txtUpdateAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 600, 31));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("CONTACT NUMBER");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, -1));

        txtUpdateContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateContactNoActionPerformed(evt);
            }
        });
        getContentPane().add(txtUpdateContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 160, 32));

        btnReset.setBackground(new java.awt.Color(255, 102, 102));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 141, 60));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 51));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 147, 77));

        jPanel3.setBackground(new java.awt.Color(54, 33, 89));
        jPanel3.setForeground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 960, -1));

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tbdots_ui/icons8_Return_50px.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        getContentPane().add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tbdots_ui/icons8_Cancel_52px_2.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, -1, -1));

        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUpdateLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateLastnameActionPerformed

    private void txtUpdateFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateFirstnameActionPerformed

    private void txtUpdateAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateAgeActionPerformed

    private void btnUpdateMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateMaleActionPerformed

    private void txtUpdateCivilStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateCivilStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateCivilStatusActionPerformed

    private void txtUpdateContactPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateContactPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateContactPersonActionPerformed

    private void txtUpdateContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateContactNoActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        this.txtUpdatePatientID.setText("");
        this.txtUpdateLastname.setText("");
        this.txtUpdateFirstname.setText("");
        this.txtUpdateMiddlename.setText("");
        this.txtUpdateAge.setText("");
        this.txtUpdateOccupation.setText("");
        this.txtUpdateCivilStatus.setText("");
        this.txtUpdateContactPerson.setText("");
        this.txtUpdateContactNo.setText("");
        this.txtUpdateAddress.setText("");
        btnUpdateMale.setSelected(true);
        //reset jdatechooser text
        jUpdateBirthdate.setDate(null);
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(SQLite.openDB()){
            int PatientID = Integer.parseInt(this.txtUpdatePatientID.getText());
            String lastname = this.txtUpdateLastname.getText();
            String firstname = this.txtUpdateFirstname.getText();
            String middlename = this.txtUpdateMiddlename.getText();

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String birthdate = dateFormat.format(jUpdateBirthdate.getDate());
            String age = this.txtUpdateAge.getText();

            String sex;
            String occupation = this.txtUpdateOccupation.getText();
            String civilstatus = this.txtUpdateCivilStatus.getText();
            String contactperson = this.txtUpdateContactPerson.getText();
            String contactno = this.txtUpdateContactNo.getText();
            String address = this.txtUpdateAddress.getText();

            SimpleDateFormat dateFormat1 = new SimpleDateFormat("yyyy-MM-dd");
//            String dateoftreat = dateFormat1.format(jUpdateDateOfTreatment.getDate());

            if(btnUpdateMale.isSelected()){
                sex = "M";
            }else{
                sex = "F";
            }
            
            String set = "PATIENTID = '"+PatientID+"'"+", LASTNAME = '"+lastname+"'"+", FIRSTNAME='"+firstname+"',"+"MIDDLENAME='"+middlename+"'"+",BIRTHDATE='"+birthdate+"'"+",AGE='"+age+"'"+",BIRTHDATE='"+birthdate+"'"+",SEX='"+sex+"'"+",OCCUPATION='"+occupation+"'"+",CIVILSTATUS='"+civilstatus+"'"+",CONTACTPERSON='"+contactperson+"'"+",CONTACTNO='"+contactno+"'"+",ADDRESS='"+address+"'";
            System.out.println(set);
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Please Confirm Action", "Would you like to Update?", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION) {
                System.out.println("Yes");
                SQLite.update("Info",set, PatientID);
            } else if(dialogResult == JOptionPane.NO_OPTION){
                System.out.println("NO");
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(null, "Error!!");
            }

            if(SQLite.update("Patient", set, PatientID)){
                javax.swing.JOptionPane.showMessageDialog(null, "Patient has been updated!");
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(null, "Error!");
            }
            SQLite.closeDB();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        FramePatient F1 = new FramePatient();
        F1.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        try {

            SQLite.conn = getConnection(SQLite.url);
            SQLite.stmt = SQLite.conn.createStatement();

            //            int id = Integer.parseInt(this.txtUpdateID.getText());
            int id = Integer.parseInt(txtUpdatePatientID.getText());
            java.sql.ResultSet rs = SQLite.stmt.executeQuery("SELECT * FROM Patient WHERE PATIENTID="+id+"");
            while(rs.next()){
                String lastname = rs.getString("LASTNAME");
                String firstname = rs.getString("FIRSTNAME");
                String middlename = rs.getString("MIDDLENAME");
                String birthdate = rs.getString("BIRTHDATE");
                String age = rs.getString("AGE");
                String sex = rs.getString("SEX");
                String occupation = rs.getString("OCCUPATION");
                String civilstatus = rs.getString("CIVILSTATUS");
                String contactperson = rs.getString("CONTACTPERSON");
                String contactno = rs.getString("CONTACTNO");
                String address = rs.getString("ADDRESS");
//                String dateoftreatment = rs.getString("DATEOFTREATMENT");

                try{

                }catch(Exception e){

                }

                //                System.out.println("Name: "+name);
                //                System.out.println("Contact: "+contact);
                //                System.out.println("Address: "+address);
                //                System.out.println("Gender: "+gender);
//                lblFname.setText(firstname);
                txtUpdateLastname.setText(lastname);
                txtUpdateFirstname.setText(firstname);
                txtUpdateMiddlename.setText(middlename);
                txtUpdateAge.setText(age);
                //retrieve birthday
                Date jubdate = new SimpleDateFormat("yyyy-MM-dd").parse(birthdate);
                jUpdateBirthdate.setDate(jubdate);
                //retrieve dateoftreatment
//                Date jtreatment = new SimpleDateFormat("yyyy-MM-dd").parse(dateoftreatment);
//                jUpdateDateOfTreatment.setDate(jtreatment);
                txtUpdateOccupation.setText(occupation);
                txtUpdateCivilStatus.setText(civilstatus);
                txtUpdateContactPerson.setText(contactperson);
                txtUpdateContactNo.setText(contactno);
                txtUpdateAddress.setText(address);

                if(sex.equals("M")){
                    btnUpdateMale.setSelected(true);
                    btnUpdateFemale.setSelected(false);
                }else{
                    btnUpdateMale.setSelected(false);
                    btnUpdateFemale.setSelected(true);
                }
            }
            conn.close();
        }
        catch (Exception e) {
            System.out.println("Error: "+e);
        }
    }//GEN-LAST:event_btnLoadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePatientUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePatientUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePatientUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePatientUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePatientUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JRadioButton btnUpdateFemale;
    private javax.swing.JRadioButton btnUpdateMale;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private com.toedter.calendar.JDateChooser jUpdateBirthdate;
    private javax.swing.JLabel lblBack;
    private javax.swing.JTextField txtUpdateAddress;
    private javax.swing.JTextField txtUpdateAge;
    private javax.swing.JTextField txtUpdateCivilStatus;
    private javax.swing.JTextField txtUpdateContactNo;
    private javax.swing.JTextField txtUpdateContactPerson;
    private javax.swing.JTextField txtUpdateFirstname;
    private javax.swing.JTextField txtUpdateLastname;
    private javax.swing.JTextField txtUpdateMiddlename;
    private javax.swing.JTextField txtUpdateOccupation;
    private javax.swing.JTextField txtUpdatePatientID;
    // End of variables declaration//GEN-END:variables
}
