/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tbdots_ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import static java.sql.DriverManager.getConnection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jekko
 */
public class FrameDoctorUpdate extends javax.swing.JFrame {
    java.sql.Connection conn  = null;
    java.sql.Statement stmt = null;
//    static String url = "jdbc:sqlite:C:\\Users\\Jekko\\Documents\\NetBeansProjects\\TBDOTS_UI\\src\\tbdots_ui\\db.sqlite";

    
    public FrameDoctorUpdate() {
        initComponents();
        setCenterFrame();
//        changeIcon();
        this.setResizable(false);
    }
    public void setCenterFrame(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
//    public void changeIcon(){
//        ImageIcon icon = new ImageIcon("src/TBDOTS_UI/ddhlogo1.jpg");
//        this.setIconImage(icon.getImage());
//    }
//        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblBack = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtUpdateDocFirstname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUpdateDocMiddlename = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUpdateDocLastname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUpdateDocContactNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtUpdateDocSpecialization = new javax.swing.JTextField();
        btnResetDoc = new javax.swing.JButton();
        btnUpdateFemale = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        btnUpdateMale = new javax.swing.JRadioButton();
        btnUpdateDoc = new javax.swing.JButton();
        txtUpdateDoctorID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnLoad = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Update Doctor Info");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jPanel4.setBackground(new java.awt.Color(54, 33, 89));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 40));

        jPanel5.setBackground(new java.awt.Color(54, 33, 89));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 670, 40));

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tbdots_ui/icons8_Return_50px.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        getContentPane().add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tbdots_ui/icons8_Cancel_52px_2.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, -1));

        txtUpdateDocFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateDocFirstnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUpdateDocFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 204, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("FIRSTNAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));
        getContentPane().add(txtUpdateDocMiddlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 204, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("MIDDLENAME:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        txtUpdateDocLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateDocLastnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUpdateDocLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 204, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("LASTNAME:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("CONTACT NO");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, -1, -1));
        getContentPane().add(txtUpdateDocContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 204, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("SPECIALIZATION");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, -1, -1));

        txtUpdateDocSpecialization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateDocSpecializationActionPerformed(evt);
            }
        });
        getContentPane().add(txtUpdateDocSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 204, 30));

        btnResetDoc.setBackground(new java.awt.Color(255, 102, 102));
        btnResetDoc.setText("RESET");
        btnResetDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetDocActionPerformed(evt);
            }
        });
        getContentPane().add(btnResetDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 90, 50));

        buttonGroup1.add(btnUpdateFemale);
        btnUpdateFemale.setText("Female");
        getContentPane().add(btnUpdateFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("SEX");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, 20));

        buttonGroup1.add(btnUpdateMale);
        btnUpdateMale.setText("Male");
        btnUpdateMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMaleActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        btnUpdateDoc.setBackground(new java.awt.Color(255, 255, 0));
        btnUpdateDoc.setText("UPDATE");
        btnUpdateDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDocActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 130, 50));
        getContentPane().add(txtUpdateDoctorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 100, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("DOCTOR NO");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 80, 30));

        jPanel6.setBackground(new java.awt.Color(54, 33, 89));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 670, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        FrameDoctor F1 = new FrameDoctor();
        F1.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void txtUpdateDocFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateDocFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateDocFirstnameActionPerformed

    private void txtUpdateDocLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateDocLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateDocLastnameActionPerformed

    private void txtUpdateDocSpecializationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateDocSpecializationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateDocSpecializationActionPerformed

    private void btnResetDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetDocActionPerformed
        this.txtUpdateDoctorID.setText("");
        this.txtUpdateDocLastname.setText("");
        this.txtUpdateDocFirstname.setText("");
        this.txtUpdateDocMiddlename.setText("");
        btnUpdateMale.setSelected(true);
        this.txtUpdateDocContactNo.setText("");
        this.txtUpdateDocSpecialization.setText("");
    }//GEN-LAST:event_btnResetDocActionPerformed

    private void btnUpdateMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateMaleActionPerformed

    private void btnUpdateDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDocActionPerformed
        if(SQLite.openDB()){
            int DoctorNo = Integer.parseInt(this.txtUpdateDoctorID.getText());
            String firstname = this.txtUpdateDocFirstname.getText();
            String middlename = this.txtUpdateDocMiddlename.getText();
            String lastname = this.txtUpdateDocLastname.getText();
            String sex;
            String contactNo = this.txtUpdateDocContactNo.getText();
            String specialization = this.txtUpdateDocSpecialization.getText();

            if(btnUpdateMale.isSelected()){
                sex = "M";
            }else{
                sex = "F";
            }
                                                                    
            String set = "DOCTORNO = '"+DoctorNo+"'"+", FIRSTNAME = '"+firstname+"'"+", MIDDLENAME='"+middlename+"',"+"LASTNAME='"+lastname+"'"+",GENDER='"+sex+"'"+",CONTACTNO='"+contactNo+"'"+",SPECIALIZATION='"+specialization+"'";
            //            String values = id +"," +"'" + firstname +"'"+","+"'"+middlename+"'"+","+"'"+lastname+"'" +","+"'"+sex+"'" +","+"'"+contactNo+"'" +","+"'"+specialization+"'";
         
            System.out.println(set);
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Please Confirm Action", "Would you like to Update?", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION) {
                System.out.println("Yes");
                SQLite.updateDoctor("Info",set, DoctorNo);
            } else if(dialogResult == JOptionPane.NO_OPTION){
                System.out.println("NO");
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(null, "Error!!");
            }

            if(SQLite.updateDoctor("Doctor", set, DoctorNo)){
                javax.swing.JOptionPane.showMessageDialog(null, "Doctor has been updated!");
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(null, "Error!");
            }
            SQLite.closeDB();
        }
    }//GEN-LAST:event_btnUpdateDocActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        try {

            SQLite.conn = getConnection(SQLite.url);
            SQLite.stmt = SQLite.conn.createStatement();

            //            int id = Integer.parseInt(this.txtUpdateID.getText());
            int id = Integer.parseInt(txtUpdateDoctorID.getText());
            java.sql.ResultSet rs = SQLite.stmt.executeQuery("SELECT * FROM Doctor WHERE DOCTORNO="+id+"");
            while(rs.next()){

                String firstname = rs.getString("FIRSTNAME");
                String middlename = rs.getString("MIDDLENAME");
                String lastname = rs.getString("LASTNAME");
                String sex = rs.getString("GENDER");
                String contactno = rs.getString("CONTACTNO");
                String specialization = rs.getString("SPECIALIZATION");

                try{

                }catch(Exception e){

                }

                //                System.out.println("Name: "+name);
                //                System.out.println("Contact: "+contact);
                //                System.out.println("Address: "+address);
                //                System.out.println("Gender: "+gender);
                txtUpdateDocLastname.setText(lastname);
                txtUpdateDocFirstname.setText(firstname);
                txtUpdateDocMiddlename.setText(middlename);

                txtUpdateDocContactNo.setText(contactno);
                txtUpdateDocSpecialization.setText(specialization);

                if(sex.equals("M")){
                    btnUpdateMale.setSelected(true);
                    btnUpdateFemale.setSelected(false);
                }else{
                    btnUpdateMale.setSelected(false);
                    btnUpdateFemale.setSelected(true);
                }
            }
            conn.close();
        }
        catch (Exception e) {
            System.out.println("Error: "+e);
        }
    }//GEN-LAST:event_btnLoadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDoctorUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDoctorUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDoctorUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDoctorUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDoctorUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnResetDoc;
    private javax.swing.JButton btnUpdateDoc;
    private javax.swing.JRadioButton btnUpdateFemale;
    private javax.swing.JRadioButton btnUpdateMale;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblBack;
    private javax.swing.JTextField txtUpdateDocContactNo;
    private javax.swing.JTextField txtUpdateDocFirstname;
    private javax.swing.JTextField txtUpdateDocLastname;
    private javax.swing.JTextField txtUpdateDocMiddlename;
    private javax.swing.JTextField txtUpdateDocSpecialization;
    private javax.swing.JTextField txtUpdateDoctorID;
    // End of variables declaration//GEN-END:variables
}
