/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tbdots_ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import static java.sql.DriverManager.getConnection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jekko
 */
public class FrameTreatmentAdd extends javax.swing.JFrame {
    java.sql.Connection conn  = null;
    java.sql.Statement stmt = null;
    static String url = "jdbc:sqlite:C:\\Users\\Jekko\\Documents\\NetBeansProjects\\TBDOTS_UI\\src\\tbdots_ui\\db.sqlite";
    String[][] records;;;
    String lastname, firstname, middlename, contactno;
    /**
     * Creates new form FrameTreatmentAdd
     */
    public FrameTreatmentAdd() {
         initComponents();
        setCenterFrame();
        changeIcon();
        this.setResizable(false);
        
        setComboBox();
        
        
    }
    
   
    void setComboBox(){
       
                
        if(SQLite.openDB()){
            records = SQLite.read("Doctor");
            String[] doctors = new String[records.length+1];
            doctors[0] = " ";
            for(int i=1,j=0;j<records.length;i++,j++){
                doctors[i] = records[j][3]+", "+records[j][1]+" "+records[j][2];
            }
            

            cmdDoctors.setModel(new javax.swing.DefaultComboBoxModel(doctors));
            SQLite.closeDB();
        }
        
        
    }
     public void setCenterFrame(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    public void changeIcon(){
        ImageIcon icon = new ImageIcon("src/TBDOTS_UI/ddhlogo1.jpg");
       this.setIconImage(icon.getImage());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jEndTreatment = new com.toedter.calendar.JDateChooser();
        jStartTreatment = new com.toedter.calendar.JDateChooser();
        lblFirstname = new javax.swing.JLabel();
        btnLoad = new javax.swing.JButton();
        lblMiddlename = new javax.swing.JLabel();
        lblLastname = new javax.swing.JLabel();
        cmdDoctors = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnAddDoc = new javax.swing.JButton();
        lblDoctorID = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLastVisit = new com.toedter.calendar.JDateChooser();
        lblBack = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("PATIENT ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 154, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Doctor ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Start Treatment");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        txtPatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 78, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("FIRSTNAME:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("MIDDLENAME: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("LASTNAME:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Last Visit");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("End Treatment");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, 20));
        getContentPane().add(jEndTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 141, 30));
        getContentPane().add(jStartTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 141, 30));

        lblFirstname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFirstname.setText("firstname");
        getContentPane().add(lblFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 230, -1));

        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 70, 30));

        lblMiddlename.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMiddlename.setText("middlename");
        getContentPane().add(lblMiddlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 220, 20));

        lblLastname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLastname.setText("lastname");
        getContentPane().add(lblLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 190, -1));

        cmdDoctors.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmdDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDoctorsActionPerformed(evt);
            }
        });
        getContentPane().add(cmdDoctors, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 270, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setText("ADD TREATMENT DATES");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));
        jPanel2.setForeground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 690, 40));

        jPanel6.setBackground(new java.awt.Color(54, 33, 89));
        jPanel6.setForeground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 20));

        jPanel3.setBackground(new java.awt.Color(54, 33, 89));
        jPanel3.setForeground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 90, 700, 20));

        btnAddDoc.setBackground(new java.awt.Color(255, 255, 0));
        btnAddDoc.setText("REGISTER");
        btnAddDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDocActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 140, 60));

        lblDoctorID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDoctorID.setText("0");
        getContentPane().add(lblDoctorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 30, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Fullname:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));
        getContentPane().add(jLastVisit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 141, 30));

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tbdots_ui/icons8_Return_50px.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        getContentPane().add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tbdots_ui/icons8_Cancel_52px_2.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        btnReset.setBackground(new java.awt.Color(255, 102, 102));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientIDActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        try {

            SQLite.conn = getConnection(SQLite.url);
            SQLite.stmt = SQLite.conn.createStatement();

            //            int id = Integer.parseInt(this.txtUpdateID.getText());
            int id = Integer.parseInt(txtPatientID.getText());
            java.sql.ResultSet rs = SQLite.stmt.executeQuery("SELECT * FROM Patient WHERE PATIENTID="+id+"");
            while(rs.next()){
                this.lastname = rs.getString("LASTNAME");
                this.firstname = rs.getString("FIRSTNAME");
                this.middlename = rs.getString("MIDDLENAME");
                this.contactno = rs.getString("contactNo");
                
               

                try{

                }catch(Exception e){

                }
                
                lblFirstname.setText(firstname);
                lblMiddlename.setText(middlename);
                lblLastname.setText(lastname);

                
            }
            conn.close();
        }
        catch (Exception e) {
            System.out.println("Error: "+e);
        }
    }//GEN-LAST:event_btnLoadActionPerformed

    private void cmdDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDoctorsActionPerformed
        int selectedIndex = cmdDoctors.getSelectedIndex();
        if(selectedIndex>0){
            lblDoctorID.setText(records[selectedIndex-1][0]);
        }
    }//GEN-LAST:event_cmdDoctorsActionPerformed

    private void btnAddDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDocActionPerformed
        if(SQLite.openDB()){
              String id = this.txtPatientID.getText();
              String doctor = lblDoctorID.getText();
              System.out.println(doctor);
              
              SimpleDateFormat dateFormat1 = new SimpleDateFormat("yyyy-MM-dd");
              String starttreat = dateFormat1.format(jStartTreatment.getDate());
             
              java.sql.Date dt = new java.sql.Date(jStartTreatment.getDate().getTime());
              Calendar cal = Calendar.getInstance();
              cal.setTime(dt);
              cal.add(Calendar.MONTH, +2);
              Date nextVisit = cal.getTime();
              System.out.println("next visit:" +nextVisit);
              String nvisit = nextVisit.toString();
              
//            
              SimpleDateFormat dateFormat2 = new SimpleDateFormat("yyyy-MM-dd");
              String lastvisit = dateFormat2.format(jLastVisit.getDate());
              
              SimpleDateFormat dateFormat3 = new SimpleDateFormat("yyyy-MM-dd");
              String endtreat = dateFormat3.format(jEndTreatment.getDate());
              
           
//              String values = id+",'"+doctor+"','"+lastvisit+"','"+endtreat+"'";
//            String values = id +","+"'" + doctor +"'"+ "'" + lastvisit +"'"+","+"'"+endtreat+"'";
              String values = id+","  + doctor +","+ "'" + starttreat +"'"+","+ "'" + lastvisit +"'"+","+ "'" + endtreat +"'";
//            String values = id+"," + "" + doctor +""+","+ "'" + starttreat +"'"+","+ "'" + lastvisit +"'"+","+ "'" + endtreat +"'";
              
            
             
              
              
              
            
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this,  "Save Changes?", "Please Confirm Action", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION) {
                System.out.println("Yes");
            } else if(dialogResult == JOptionPane.NO_OPTION){
                System.out.println("NO");
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(null, "Error!!");
            }

            if(SQLite.createTreatment("Treatment", values)){
                javax.swing.JOptionPane.showMessageDialog(null, "New Treatment has been added!");
                //insert into dbo.notifcation
                try{
                    SQLite.conn = getConnection(SQLite.url);
                    SQLite.stmt = SQLite.conn.createStatement();
//                    String notifValues = "'"+this.firstname+"', '"+this.lastname+"', '"+this.middlename+"', '"+this.contactno+"', '"+nvisit+"'";
                    String queryInsert = "INSERT INTO Notification (P_Fname, P_Mname, P_Lname, "
                            +"contactNumber, nextVisit) VALUES ('"+this.firstname+"', '"+this.middlename+"', '"
                            +this.lastname+"', '"+this.contactno+"', '"+nvisit+"')";
                    SQLite.stmt.executeUpdate(queryInsert);
                    JOptionPane.showMessageDialog(null, "Next Visit: "+nvisit);

                    SQLite.conn.close();
//                    SQLite.stmt.close();
                }catch(SQLException e){
                    System.out.println("Notfication - Insert Error");
                }
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(null, "Error!");
            }
            SQLite.closeDB();
        }
    }//GEN-LAST:event_btnAddDocActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        FrameTreatment F1 = new FrameTreatment();
        F1.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        this.txtPatientID.setText("");
        this.lblFirstname.setText("");
        this.lblMiddlename.setText("");
        this.lblLastname.setText("");
        this.lblDoctorID.setText("");
        this.cmdDoctors.setSelectedIndex(0);
        //reset jdatechooser text
        jStartTreatment.setDate(null);
        jLastVisit.setDate(null);
        jEndTreatment.setDate(null);

    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTreatmentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTreatmentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTreatmentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTreatmentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTreatmentAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDoc;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox cmdDoctors;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jEndTreatment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser jLastVisit;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private com.toedter.calendar.JDateChooser jStartTreatment;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblDoctorID;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblMiddlename;
    private javax.swing.JTextField txtPatientID;
    // End of variables declaration//GEN-END:variables
}
